### ISSUE TITLE
Notebook produces errors in Colab

### ISSUE THREAD

**Issue by xbotuk** [ceshine/apex_pytorch_cifar_experiment#1]
I have loaded wide_resnet_10epochs_O2.ipynb in Colab and then started running cell by cell.

What file did you upload in cell 3?

Also on cell 4 I am getting the below error. Do you have the underlying telegram_tokens package that you used for the notebook?

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-9b2d36be91c7> in <module>()
     17 from apex.optimizers import FusedAdam
     18 
---> 19 from baseline import (
     20     CifarBot, get_cifar10_dataset,
     21     get_wide_resnet, get_se_resnext,

/content/baseline.py in <module>()
     24 from telegram_sender import telegram_sender
     25 from wide_resnet import Wide_ResNet
---> 26 from telegram_tokens import BOT_TOKEN, CHAT_ID
     27 
     28 TRANSFORM_TRAIN = transforms.Compose([

ModuleNotFoundError: No module named 'telegram_tokens'`

**Comment by ceshine** [comment]
I used telegram bot API to notify me when the training is completed. The sample file is provided as [telegram_tokens.py.sample](https://github.com/ceshine/apex_pytorch_cifar_experiment/blob/master/telegram_tokens.py.sample). You can remove the notification [here](https://github.com/ceshine/apex_pytorch_cifar_experiment/blob/master/apex_trainer.py#L27) if you don't have telegram tokens.

Correction: 
You'll need to remove all links to `telegram_tokens.py` as well.

A better way might be to implement a noop in [telegram_sender.py](https://github.com/ceshine/apex_pytorch_cifar_experiment/blob/master/telegram_sender.py) when the passed token is empty or None. I've done that in another project, but haven't ported it here.
